name: List Repository Commits

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  list_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install @octokit/rest

      - name: Fetch Commits using Octokit
        env:
          owner: my-repo-owner # Replace with the owner of the repo
          repo: my-repo-name   # Replace with the repository name
        uses: actions/github-script@v7
        with:
          script: |
            let page = 1;
            const perPage = 100; // Number of commits per page
            let firstCommit = null;
            
            while (true) {
                const response = await github.rest.repos.listCommits({
                    owner: 'Rudra-SH',
                    repo: 'rudra_repo',
                    sha: 'main', // Replace with the default branch name if it's not 'main'
                    per_page: perPage,
                    page,
                });
            
                if (response.data.length === 0) {
                    throw new Error('No commits found in the repository.');
                }
            
                // If this is the last page, get the oldest commit
                if (response.data.length < perPage) {
                    firstCommit = response.data[response.data.length - 1];
                    break;
                }
            
                page++;
            }
            
            // Validate the date of the first commit
            const firstCommitDate = new Date(firstCommit.commit.author.date);
            const sixMonthsAgo = new Date();
            sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);
            
            if (firstCommitDate < sixMonthsAgo) {
                throw new Error(`The repository's first commit is older than 6 months: ${firstCommitDate}`);
            }
            
            // Log the first commit SHA if the date is within 6 months
            console.log('First Commit SHA:', firstCommit.sha);
