name: Get CODEOWNERS Content

on:
  push:
    branches:
      - getCodeOwnersContents

jobs:
  get_codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensures CODEOWNERS is available locally

      - name: Extract Org & Team Names
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Define CODEOWNERS path
            const codeownersPath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'CODEOWNERS');

            if (!fs.existsSync(codeownersPath)) {
              console.log("CODEOWNERS file not found.");
              return;
            }

            // Read CODEOWNERS content
            const content = fs.readFileSync(codeownersPath, 'utf-8');

            // Remove comments and extract team names
            const lines = content.split('\n')
              .map(line => line.trim()) // Remove leading/trailing spaces
              .filter(line => line && !line.startsWith('#')); // Remove comments & empty lines

            // Extract teams (pattern: @org/team)
            const teamRegex = /@([\w-]+)\/([\w-]+)/g;
            let orgNames = [];
            let teamNames = [];

            for (const line of lines) {
              let match;
              while ((match = teamRegex.exec(line)) !== null) {
                orgNames.push(match[1]);  // orgName
                teamNames.push(match[2]); // teamName
              }
            }

            console.log("Org Names:", orgNames);
            console.log("Team Names:", teamNames);
