name: Get CODEOWNERS Content

on:
  push:
    branches:
      - getCodeOwnersContents

jobs:
  get_codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensures CODEOWNERS is available locally

      - name: Extract Org & Team Names
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.getContent({
              owner: 'Rudra-SH',
              repo: 'rudra_repo',
              path: '.github/CODEOWNERS'
            });

            const codeowners_response = response.data;
            const codeowners_base64_content = codeowners_response.content;
            const codeowners_contents = atob(codeowners_base64_content.replace(/[^A-Za-z0-9_=-]/g, ''));

            console.log("Raw CODEOWNERS Content:\n", codeowners_contents);

            const patterns = new Set();
            const teams = new Set();

            const lines = codeowners_contents.split('\n');

            lines.forEach(line => {
              // Remove comments (both inline and full-line comments)
              const cleanedLine = line.split('#')[0].trim();

              // Skip empty lines
              if (!cleanedLine) return;

              // Extract pattern and team names, handling multiple spaces
              const parts = cleanedLine.split(/\s+/);
              if (parts.length > 1) {
                patterns.add(parts[0]); // Add pattern
                parts.slice(1).forEach(team => teams.add(team)); // Add teams
              }
            });

            console.log("Extracted Patterns:", Array.from(patterns));
            console.log("Extracted Teams:", Array.from(teams));
