name: Get CODEOWNERS Content

on:
  push:
    branches:
      - getCodeOwnersContents

jobs:
  get_codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensures CODEOWNERS is available locally

      - name: Extract Org & Team Names
        uses: actions/github-script@v7
        with:
          script: |
            
            const response = await github.rest.repos.getContent({
              owner: 'Rudra-SH',
              repo: 'rudra_repo',
              path: '.github/CODEOWNERS'
            });

            const codeowners_response = response.data;
            console.log(codeowners_response);

            const codeowners_base64_content = codeowners_response.content.trim();

            const codeowners_contents = atob(codeowners_base64_content.replace(/[^A-Za-z0-9_=-]/g, ''));
            const lines = codeowners_contents.split('\n');
            console.log(lines);

            const patterns = [];
            const teams = [];

            lines.forEach(line => {
              const parts = line.trim().split(/\s+/);
              if(parts.length > 1) {
                patterns.push(parts[0]);
                teams.push(...parts.slice(1));
              }
            });

            console.log(patterns);
            console.log(teams);

            // Test 1

            
