name: Get CODEOWNERS Content

on:
  push:
    branches:
      - getCodeOwnersContents

jobs:
  get_codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensures CODEOWNERS is available locally

      - name: Extract Org & Team Names
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Define CODEOWNERS path
            const codeownersPath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'CODEOWNERS');

            if (!fs.existsSync(codeownersPath)) {
              console.log("CODEOWNERS file not found.");
              return;
            }

            // Read CODEOWNERS content
            const content = fs.readFileSync(codeownersPath, 'utf-8');

            // Remove comments and extract relevant lines
            const lines = content.split('\n')
              .map(line => line.trim()) // Remove leading/trailing spaces
              .filter(line => line && !line.startsWith('#')); // Remove comments & empty lines

            // Regex patterns for team members and individual users
            const teamRegex = /@([\w-]+)\/([\w-]+)/g; // Matches @org/team
            const userRegex = /@([\w-]+_enterpriseName)/g;

            let orgNames = [];
            let teamNames = [];
            let codeOwners = []; // To store final list of owners

            for (const line of lines) {
              let teamMatch;
              let userMatch;

              // Extract teams
              while ((teamMatch = teamRegex.exec(line)) !== null) {
                const org = teamMatch[1];  // orgName
                const team = teamMatch[2]; // teamName
                orgNames.push(org);
                teamNames.push(team);
              }

              // Extract individual users (excluding team patterns)
              while ((userMatch = userRegex.exec(line)) !== null) {
                const user = userMatch[1]; // Extract the full username with _enterpriseName
                codeOwners.push(user);
              }
            }

            console.log("Org Names:", orgNames);
            console.log("Team Names:", teamNames);
            console.log("Initial CodeOwners (only individuals):", codeOwners);
