name: Get CODEOWNERS Content

on:
  push:
    branches:
      - getCodeOwnersContents

jobs:
  get_codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Ensures CODEOWNERS is available locally

      - name: Extract Org & Team Names
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Define CODEOWNERS path
            const codeownersPath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'CODEOWNERS');

            if (!fs.existsSync(codeownersPath)) {
              console.log("CODEOWNERS file not found.");
              return;
            }

            // Read CODEOWNERS content
            let content = fs.readFileSync(codeownersPath, 'utf-8');

            // 1️⃣ Remove everything after '#' (inline comments)
            content = content.replace(/#.*$/gm, '').trim();

            console.log('content', content);

            // 2️⃣ Split into lines and remove empty ones
            const lines = content.split('\n')
              .map(line => line.trim())
              .filter(line => line.length > 0); // Remove empty lines

            console.log('lines', lines);

            // 3️⃣ Regex patterns
            const teamRegex = /@([\w-]+)\s*\/\s*([\w-]+)/g;  // @orgName/teamName (Handles spaces)
            const userRegex = /@([\w-]+_enterpriseName)/g;   // @username_enterpriseName

            let orgNames = new Set();
            let teamNames = new Set();
            let codeOwners = new Set();

            for (const line of lines) {
              let teamMatch;
              let userMatch;

              // Extract teams
              while ((teamMatch = teamRegex.exec(line)) !== null) {
                orgNames.add(teamMatch[1].trim());  // orgName
                teamNames.add(teamMatch[2].trim()); // teamName
              }

              // Extract individual users (excluding teams)
              while ((userMatch = userRegex.exec(line)) !== null) {
                codeOwners.add(userMatch[1].trim());
              }
            }

            // Convert Sets to Arrays
            orgNames = [...orgNames];
            teamNames = [...teamNames];
            codeOwners = [...codeOwners];

            console.log("Org Names:", orgNames);
            console.log("Team Names:", teamNames);
            console.log("Initial CodeOwners (only individuals):", codeOwners);
