name: Job Output Example with env

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.set-output.outputs.my_var }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set-env
        id: set-env
        uses: actions/github-script@v7
        with:
          script: |
            const branch_ref = `${{ github.ref_name }}`;
            const branch_sha = `${{ github.sha }}`;
            console.log(branch_ref);
            console.log(branch_sha);

            core.exportVariable('BRANCH_REF', branch_ref);
            core.exportVariable('BRANCH_SHA', branch_sha);

      - name: Set output
        id: set-output
        run: |
          echo "::set-output name=branch_ref::$BRANCH_REF"
          echo "::set-output name=branch_sha::$BRANCH_SHA"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use the job output
        run: echo "MY_VAR is ${{ needs.job1.outputs.my_var }}"
