name: Job Output Example with env

on: [push]
env:
  BRANCH_SHA: ${{ github.sha }}
  BRANCH_REF: ${{ github.ref_name }}

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      branch_ref: ${{ steps.set-output.outputs.BRANCH_REF }}
      branch_sha: ${{ steps.set-output.outputs.BRANCH_SHA }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: set-env
      #   id: set-env
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       //const branch_ref = `${{ github.ref_name }}`;
      #       //const branch_sha = `${{ github.sha }}`;
      #       console.log(branch_ref);
      #       console.log(branch_sha);

      #       //core.exportVariable('BRANCH_REF', branch_ref);
      #       //core.exportVariable('BRANCH_SHA', branch_sha);

      - name: Set output
        id: set-output
        uses: actions/github-script@v7
        with:
          script: |
            const branch_ref = process.env.BRANCH_REF;
            const branch_sha = process.env.BRANCH_SHA;
            console.log(branch_ref);
            console.log(branch_sha);
            /*console.log(process.env.VAR1);
            
            core.setOutput('BRANCH_REF', branch_ref);
            core.setOutput('BRANCH_SHA', branch_sha);*/

  job2:
    runs-on: ubuntu-latest
    needs: job1
    env: 
      JOB2_ENV: This is job 2env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use the job output
        env: 
          STEP_ENV: This is step env
        run: |
          #echo "BRANCH_REF is ${{ needs.job1.outputs.branch_ref }}"
          #echo "BRANCH_SHA is ${{ needs.job1.outputs.branch_sha }}"
          echo "${BRANCH_REF}";
          echo "${BRANCH_SHA}";
          echo "${STEP_ENV}";
          echo "${JOB2_ENV}";
