name: Job Output Example with env

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MY_VAR: value_from_job1
    outputs:
      my_var: ${{ steps.set-output.outputs.my_var }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set output
        id: set-output
        run: echo "::set-output name=my_var::$MY_VAR"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use the job output
        run: echo "MY_VAR is ${{ needs.job1.outputs.my_var }}"
