name: Azure DevOps Repo Clone

on:
  push:
    branches:
      - main

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run custom script
      uses: actions/github-script@v6
      with: 
        script: |
          const { execSync } = require('child_process');
          const url = process.env.ADO_REPO_URL;
  
          try {
            execSync(`git clone https://rudra099999:z5ydmufikg2jev7eutalhqqjhsjxfg7oomyzv4ezjst6lrmgnmla@dev.azure.com/rudra099999/Project%20A/_git/TestA`);
            console.log('Repository cloned successfully.');
          } catch (error) {
            console.error('Error cloning repository:', error.message);
            process.exit(1);
          }
      
