name: Demo Workflow

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is a normal step"

      - name: Step 2
        run: echo "This step has a warning"
        continue-on-error: true
        if: always()
        # Adding a warning annotation
        with:
          annotation: "This step has a warning"
          title: "Warning"

      - name: Step 3
        run: echo "This step has an error"
        continue-on-error: false
        # Adding an error annotation
        with:
          annotation: "This step has an error"
          title: "Error"

    # Add more steps as needed for your workflow
