name: Demo Workflow

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose the operating system that suits your needs

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # This action checks out your repository

    - name: Clone Another Repository
      run: |
        git clone https://rudra099999:z5ydmufikg2jev7eutalhqqjhsjxfg7oomyzv4ezjst6lrmgnmla@dev.azure.com/rudra099999/Project%20A/_git/TestA # Replace with the URL of the repository you want to clone
        cd TestA
        ls -lrt

    # Add more steps as needed for your workflow
