name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Step 1
        run: echo "This is a normal step"

      - name: Step 2 with warning
        run: |
          echo "::warning file=example.txt::This is a warning message"
          echo "This is the actual command that runs"

      - name: Step 3 with error
        run: |
          echo "::error file=example.txt::This is an error message"
          #exit 1  # This step will result in an error

      - name: Step 4 after error
        run: echo "This step won't run if the previous step has an error"
