name: Test triggering
on:
  workflow_dispatch:
    inputs:
      step1:
        description: 'Step1 Input'
        required: true
      step2:
        description: 'Step2 Input'
        required: true
      step3:
        description: 'Step1 Input'
        required: true
        

jobs:
  test-triggerring:
    runs-on: ubuntu-latest
    steps:

    - name: Check for Teams Webhook URL
      id: check_teams_webhook
      run: |
        if [ -z "${{ secrets.TEAMS_WEBHOOK_URL }}" ]; then
          echo "::set-output name=has_webhook::false"
        else
          echo "::set-output name=has_webhook::true"
        fi
    
    - name: Step 1
      if: steps.check_teams_webhook.outputs.has_webhook == 'true'
      run: |
        echo "Step 1 Input"
        echo ${{ inputs.step1 }}

    - name: Step 2
      run: |
        echo "Step 2 Input"
        echo ${{ inputs.step1 }}
        echo "::error::error in step 2"

    - name: Step 3
      run: |
        echo "Step 3 Input"
        echo ${{ inputs.step1 }}
