name: Azure DevOps Repo Clone

on:
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run custom script
      uses: actions/github-script@v6
      with: 
        script: |
          let packageModule = 'Custom';
          let qualityCheckModule = 'Custom';
          let issue_app_type = 'Liberty';

          if(packageModule === 'Custom' || qualityCheckModule ==='Custom'){
            console.log('valid')
            return;
          }
          
          if (['Websphere', 'Liberty', 'Mulesoft', 'ZOS'].includes(issue_app_type)){
              if((packageModule === 'maven' && (qualityCheckModule === 'maven' || qualityCheckModule === 'sonar')) || (packageModule === 'Custom' && qualityCheckModule === 'Custom')){
                  console.log('Valid');
              } else{
                  console.log(`invalid`);
              }
          }
      
