name: Upload Artifact

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install @actions/artifact

      - name: Upload artifact to run
        uses: actions/github-script@v7
        with:
          script: |
            const artifact = require('@actions/artifact');
            const coreLib = require('@actions/core'); // Renamed to avoid conflict
            
            async function uploadArtifact() {
                const artifactClient = new artifact();
                const artifactName = 'artifacts';
                const files = ['artifact1.txt']; // List of file paths
                const rootDirectory = './artifacts'; // Root directory of the files
            
                try {
                    const response = await artifactClient.uploadArtifact(
                      artifactName,
                      files,
                      rootDirectory,
                      { retentionDays: 30 }
                    );
                    coreLib.info(`Artifact uploaded: ${response.artifactName}`);
                } catch (error) {
                    coreLib.setFailed(`Failed to upload artifact: ${error.message}`);
                }
            }
            
            uploadArtifact();
